### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by 0xB10C** [darosior/website#1]
Consider adding an RSS feed https://gohugo.io/templates/rss/

Should be something like adding this to hugo.toml

```toml
[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
```
